title: Meu Site
description: Um site simples com GitHub Pages e Jekyll
theme: jekyll-theme-primer
source: docs
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter
